"""
agents/scribe.py
─────────────────
Subagent 4: Clinical Dossier Writer (The Scribe)

Responsibility:
  - Input:  verified_matches + clean_fhir_json + pipeline stats from state
  - Output: report_markdown stored in state (also written to disk by main.py)

What it does:
  Generates a beautifully structured Markdown dossier for the physician.

  The report contains three required sections:
    1. Executive Summary  — checklist of why the patient qualifies
    2. Trial Breakdown Table — NCT ID | Official Title | Phase | Location
    3. Next Steps         — direct enrollment contact information

  If no trials matched, the report still generates with a dignified
  "No Eligible Trials Found" section rather than crashing.

Design note:
  We use Claude for report generation (rather than Python f-strings) because
  the eligibility_summary fields are natural language and benefit from
  Claude's ability to synthesize them into a coherent executive narrative.
  The Python code then does a post-process to ensure the table structure
  is correctly formatted regardless of Claude's Markdown habits.
"""

from __future__ import annotations

import os
from datetime import datetime

import anthropic

from utils.logger import get_logger
from utils.state import PipelineState

logger = get_logger(__name__)

_MODEL: str = os.environ.get("CLAUDE_MODEL", "claude-sonnet-4-6")

# ── System prompt ─────────────────────────────────────────────────────────────

_SYSTEM_PROMPT = """You are a clinical research coordinator writing a physician-facing dossier.

You will receive:
1. An anonymized patient profile
2. A list of verified eligible clinical trials

Write a clean, highly scannable Markdown report with these EXACT sections:

---

# Clinical Trial Candidate Dossier
**Generated:** {date}
**Status:** Confidential — For Physician Review Only

---

## Patient Profile Summary
[2-3 sentence overview of the patient's key clinical features relevant to trial eligibility. No PII.]

---

## ✅ Executive Summary — Eligibility Checklist
[For each verified trial, one bullet point: "✓ **NCT ID** — one sentence on why this patient qualifies."]

---

## Trial Breakdown

| NCT ID | Official Title | Phase | Primary Location |
|--------|---------------|-------|-----------------|
[One row per verified trial]

---

## Trial Details

[For each verified trial, include a subsection:]

### [NCT ID] — [Official Title]
**Phase:** [phase]
**Location:** [primary location]

**Why This Patient Qualifies:**
[2-3 bullet points from the eligibility summary]

---

## 📞 Next Steps — Enrollment Contact Information

| NCT ID | Contact Name | Email | Phone |
|--------|-------------|-------|-------|
[One row per trial with contact info. Use "Not provided" for missing fields.]

---

## Pipeline Summary
- Trials fetched from ClinicalTrials.gov: {total_fetched}
- Trials evaluated: {total_evaluated}
- Eligible matches: {total_matches}
- Rejected (ineligible): {total_rejected}

---
*Report generated by Automated Clinical Trial Matcher MVP*
*This dossier is for clinical decision support only and does not constitute medical advice.*

---

RULES:
- Use Markdown tables with proper alignment pipes
- Do NOT include any patient PII
- Keep language clinical and precise
- Output ONLY the Markdown — no preamble
"""


# ── Agent class ───────────────────────────────────────────────────────────────

class ScribeAgent:
    """
    Subagent 4: Generates the physician-facing Markdown dossier.
    """

    def __init__(self) -> None:
        self.client = anthropic.Anthropic(
            api_key=os.environ.get("ANTHROPIC_API_KEY")
        )
        self.model = _MODEL
        logger.info(f"ScribeAgent initialized with model={self.model}")

    def run(self, state: PipelineState) -> PipelineState:
        """
        Generate the clinical dossier from verified matches.

        Args:
            state: Pipeline state with verified_matches.

        Returns:
            Updated state with report_markdown populated.
        """
        logger.info("─── Subagent 4: Scribe started ───")

        try:
            if not state.verified_matches:
                logger.warning("No verified matches — generating 'no results' report")
                state.report_markdown = self._generate_no_results_report(state)
            else:
                state.report_markdown = self._call_claude(state)

            logger.info(f"Scribe complete — report length: {len(state.report_markdown)} chars")

        except anthropic.APIError as exc:
            logger.error(f"Anthropic API error in Scribe: {exc}")
            # Fall back to a structured Python-generated report
            state.report_markdown = self._fallback_report(state)
            state.add_error(
                agent="ScribeAgent",
                error_type="APIError",
                message=f"Fell back to template report: {exc}",
                recoverable=True,
            )
        except Exception as exc:
            logger.error(f"Unexpected error in Scribe: {exc}", exc_info=True)
            state.report_markdown = self._fallback_report(state)
            state.add_error(
                agent="ScribeAgent",
                error_type="UnexpectedError",
                message=str(exc),
                recoverable=True,
            )

        return state

    def _call_claude(self, state: PipelineState) -> str:
        """
        Generate the full dossier using Claude.

        Returns:
            Markdown string.
        """
        # Build a concise input for Claude (not the entire raw chart)
        patient_summary = ""
        if state.clean_fhir_json:
            fhir = state.clean_fhir_json
            patient_summary = (
                f"Age: {fhir.patient.age_range}\n"
                f"Gender: {fhir.patient.gender}\n"
                f"Conditions: {', '.join(fhir.conditions)}\n"
                f"Medications: {', '.join(fhir.medications)}\n"
                f"Key Labs: {', '.join(f'{lr.test}={lr.value}{lr.unit}' for lr in fhir.lab_results[:6])}"
            )

        trials_summary = "\n\n".join([
            f"NCT ID: {m.nct_id}\n"
            f"Title: {m.official_title}\n"
            f"Phase: {m.phase}\n"
            f"Location: {m.primary_location}\n"
            f"Eligibility Summary: {m.eligibility_summary}\n"
            f"Contact: {m.contact_name or 'N/A'} | {m.contact_email or 'N/A'} | {m.contact_phone or 'N/A'}"
            for m in state.verified_matches
        ])

        system_with_stats = _SYSTEM_PROMPT.format(
            date=datetime.now().strftime("%Y-%m-%d %H:%M UTC"),
            total_fetched=state.total_trials_fetched,
            total_evaluated=state.total_trials_evaluated,
            total_matches=len(state.verified_matches),
            total_rejected=len(state.rejected_trials),
        )

        user_content = (
            f"PATIENT PROFILE:\n{patient_summary}\n\n"
            f"VERIFIED ELIGIBLE TRIALS ({len(state.verified_matches)}):\n\n"
            f"{trials_summary}"
        )

        response = self.client.messages.create(
            model=self.model,
            max_tokens=4096,
            system=system_with_stats,
            messages=[{"role": "user", "content": user_content}],
        )

        return response.content[0].text.strip()

    def _generate_no_results_report(self, state: PipelineState) -> str:
        """Generate a minimal report when no trials matched."""
        date_str = datetime.now().strftime("%Y-%m-%d %H:%M UTC")
        patient_info = ""
        if state.clean_fhir_json:
            fhir = state.clean_fhir_json
            patient_info = f"Primary Condition(s): {', '.join(fhir.conditions[:3])}"

        rejection_table = ""
        if state.rejected_trials:
            rows = "\n".join([
                f"| {t.nct_id} | {t.official_title[:50]}... | {t.rejection_reason[:80]} |"
                for t in state.rejected_trials[:10]
            ])
            rejection_table = (
                "\n## Rejected Trials (Top 10)\n\n"
                "| NCT ID | Title | Rejection Reason |\n"
                "|--------|-------|------------------|\n"
                f"{rows}\n"
            )

        return f"""# Clinical Trial Candidate Dossier
**Generated:** {date_str}
**Status:** Confidential — For Physician Review Only

---

## ⚠️ No Eligible Trials Found

{patient_info}

No clinical trials currently recruiting matched all eligibility criteria for this patient profile.

**Trials Searched:** {state.total_trials_fetched}
**Trials Evaluated:** {state.total_trials_evaluated}
**Eligible Matches:** 0

{rejection_table}

## Recommendations

- Consider broadening the search to adjacent conditions or related drug classes
- Re-evaluate in 30–60 days as new trials are continuously added to ClinicalTrials.gov
- Consult a clinical research coordinator for expanded registry options

---
*Report generated by Automated Clinical Trial Matcher MVP*
*This dossier is for clinical decision support only and does not constitute medical advice.*
"""

    def _fallback_report(self, state: PipelineState) -> str:
        """
        Minimal Python-generated report used if Claude API call fails.
        Ensures the pipeline always produces an output file.
        """
        date_str = datetime.now().strftime("%Y-%m-%d %H:%M UTC")
        lines = [
            f"# Clinical Trial Candidate Dossier (Fallback Report)",
            f"**Generated:** {date_str}",
            f"**Note:** Report was generated in fallback mode due to a Scribe API error.\n",
            "---\n",
            f"## Verified Matches ({len(state.verified_matches)})\n",
        ]

        for m in state.verified_matches:
            lines.append(f"### {m.nct_id} — {m.official_title}")
            lines.append(f"- **Phase:** {m.phase}")
            lines.append(f"- **Location:** {m.primary_location}")
            lines.append(f"- **Summary:** {m.eligibility_summary}")
            if m.contact_email or m.contact_phone:
                lines.append(f"- **Contact:** {m.contact_name} | {m.contact_email} | {m.contact_phone}")
            lines.append("")

        lines.append("---")
        lines.append("*Automated Clinical Trial Matcher MVP*")
        return "\n".join(lines)
